FROM public.ecr.aws/bitnami/spark:3.5
#DockerFile del spark
USER root

# Instalamos dependencias de Python adicionales si las necesitas en Spark
# (Como scikit-learn o pandas para el modelado)
COPY requirements.txt /opt/bitnami/spark/requirements.txt
RUN pip install --no-cache-dir -r /opt/bitnami/spark/requirements.txt

# Descargamos el conector de MongoDB para Spark
# Esto es vital para que model.save() y la escritura de streaming funcionen
ADD https://repo1.maven.org/maven2/org/mongodb/spark/mongo-spark-connector_2.12/10.2.1/mongo-spark-connector_2.12-10.2.1.jar /opt/bitnami/spark/jars/
ADD https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-sync/4.8.2/mongodb-driver-sync-4.8.2.jar /opt/bitnami/spark/jars/
ADD https://repo1.maven.org/maven2/org/mongodb/bson/4.8.2/bson-4.8.2.jar /opt/bitnami/spark/jars/

# Seteamos el directorio de trabajo
WORKDIR /opt/bitnami/spark/app

# Cambiamos permisos para que Spark pueda escribir el modelo sin errores
RUN chmod -R 777 /opt/bitnami/spark/app

USER 1001